apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ include "nginx.fullname" . }}-html-pv
spec:
  storageClassName: {{ include "nginx.fullname" . }}-html
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: {{ .Values.global.nfsHost }}
    path: {{ .Values.global.nfsPath }}/app
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ include "nginx.fullname" . }}-layout-pv
spec:
  storageClassName: {{ include "nginx.fullname" . }}-layout
  capacity:
    storage: 50Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: {{ .Values.global.nfsHost }}
    path: {{ .Values.global.nfsPath }}/app/custom/layouts/ibs_layout
  persistentVolumeReclaimPolicy: Retain