apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ include "nginx.fullname" . }}-html-pv
spec:
  storageClassName: {{ include "nginx.fullname" . }}-html
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.global.nfsPath }}/app
    server: {{ .Values.global.nfsHost }}
