apiVersion: v1
kind: PersistentVolume
metadata:
  name: rhymix-nginx-html-pv
spec:
  storageClassName: nginx-html
  capacity:
    storage: 200Mi
  accessModes:
    - ReadOnlyMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: {{ .Values.global.nfsHost }}
    path: {{ .Values.global.nfsPath }}/app/_rhymix
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rhymix-nginx-files-pv
spec:
  storageClassName: nginx-files
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
    - rw
  nfs:
    server: {{ .Values.global.nfsHost }}
    path: {{ .Values.global.nfsPath }}/files
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rhymix-nginx-layout-pv
spec:
  storageClassName: nginx-layout
  capacity:
    storage: 50Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: {{ .Values.global.nfsHost }}
    path: {{ .Values.global.nfsPath }}/app/custom/layouts/ibs_layout
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rhymix-nginx-skin-pv
spec:
  storageClassName: nginx-skin
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: {{ .Values.global.nfsHost }}
    path: {{ .Values.global.nfsPath }}/app/custom/modules/board/skins/faq
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rhymix-nginx-install-pv
spec:
  storageClassName: nginx-install
  capacity:
    storage: 5Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: {{ .Values.global.nfsHost }}
    path: {{ .Values.global.nfsPath }}/app/custom/modules/install/script
  persistentVolumeReclaimPolicy: Retain

