apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhymix-nginx-html-pvc
spec:
  storageClassName: nginx-html
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhymix-nginx-files-pvc
spec:
  storageClassName: nginx-files
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: rhymix-nginx-files-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhymix-nginx-layout-pvc
spec:
  storageClassName: nginx-layout
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Mi
  volumeName: rhymix-nginx-layout-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhymix-nginx-skin-pvc
spec:
  storageClassName: nginx-skin
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
  volumeName: rhymix-nginx-skin-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhymix-nginx-install-pvc
spec:
  storageClassName: nginx-install
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Mi
  volumeName: rhymix-nginx-install-pv
