apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ include "mariadb.primary.fullname" . }}-backup-pv
spec:
  storageClassName: dump-backup-{{ .Values.global.appMode }}
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.global.nfsPath }}/volume/backups
    server: {{ .Values.global.nfsHost }}
