apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}-secret
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
  mariadb-password: {{ .Values.auth.password | b64enc | quote }}
